encode:
  resolution:
    - [1280, 720]
    - [960, 540]

  
  framerate:
    - 15


  QP:
    - 22 

  
decode: 

videos:
    - "/home/smt/Downloads/video/testone1.yuv"
    
output:
  recordpath: "./results/delay.txt"



settings:
  save_each_h264: "off"
