encode:
  resolution:
    - [1920, 1080]
    - [1280, 720]
    - [960, 540]
    - [640, 360]
  
  framerate:
    - 15
    - 30
    - 60
    - 120

  QP:
    - 22 
    - 27
    - 32
    - 37
    - 42
  

decode: 

videos:
  - "/mnt/g/raw_videos/video/testone1.yuv"
  - "/mnt/g/raw_videos/video/testone2.yuv"
  - "/mnt/g/raw_videos/video/testone3.yuv"
  - "/mnt/g/raw_videos/video/testone4.yuv"
  - "/mnt/g/raw_videos/video/testone5.yuv"
  - "/mnt/g/raw_videos/video/testone6.yuv"
  - "/mnt/g/raw_videos/video/testone7.yuv"
